service: dsig-airtable-service

custom:
  webpack:
    webpackConfig: ./webpack.config.js
    includeModules: true

# Add the serverless-webpack plugin
plugins:
  - serverless-webpack

provider:
  name: aws
  runtime: nodejs12.x
  stage: ${opt:stage, 'dev'}
  apiGateway:
    minimumCompressionSize: 1024 # Enable gzip compression for responses > 1 KB
  iamRoleStatements:
    - Effect: 'Allow'
      Action:
        - 'SNS:Publish'
      Resource:
        - !Ref RideReportTopic
  environment:
    AWS_NODEJS_CONNECTION_REUSE_ENABLED: 1
    AIRTABLE_BASE_ID: ${ssm:/DSIG_AIRTABLE_BASE_ID_${self:provider.stage}}
    AIRTABLE_API_KEY: ${ssm:/DSIG_AIRTABLE_API_KEY}
    SLACK_WEBHOOK_URL: ${ssm:/DSIG_SLACK_WEBHOOK_URL_${self:provider.stage}}
    RIDE_REPORT_SNS_TOPIC: !Ref RideReportTopic 

functions:
  processRideReports:
    handler: src/handlers/ride-reports.handle
    events:
      - schedule:
          rate: rate(3 minutes)
          enabled: true
  postRideReportToSlack:
    handler: src/handlers/ride-report-slack.handle
    events:
      - sns: 
          arn: !Ref RideReportTopic 
          topicName: ride-reports-topic-${self:provider.stage}

resources:
  Resources:
    RideReportTopic:
      Type: AWS::SNS::Topic
      Properties:
        TopicName: ride-reports-topic-${self:provider.stage}