service:
  name: dsig-airtable-service

custom:
  webpack:
    webpackConfig: ./webpack.config.js
    includeModules: true

# Add the serverless-webpack plugin
plugins:
  - serverless-webpack

provider:
  name: aws
  runtime: nodejs12.x
  apiGateway:
    minimumCompressionSize: 1024 # Enable gzip compression for responses > 1 KB
  environment:
    AWS_NODEJS_CONNECTION_REUSE_ENABLED: 1
    AIRTABLE_BASE_ID: ${ssm:/DSIG_AIRTABLE_BASE_ID~true}
    AIRTABLE_API_KEY: ${ssm:/DSIG_AIRTABLE_API_KEY~true}

functions:
  processRideReports:
    handler: src/handlers/ride-reports.handle
    events:
      - schedule:
          rate: rate(1 minute)
          enabled: true